---
# tasks file for ansible-atlassian-bambooagent-cmake-role


- name: '[CMAKE] Checking that required variables are set'
  fail: msg="{{ item }} is not defined"
  when: item is undefined
  with_items:
    - cmake_installation
    - bambooagent_install_root

- name: "[CMAKE] OSX installation tasks"
  include_tasks: install_cmake_osx.yml
  when: ansible_distribution == 'MacOSX'

- name: "[CMAKE] Ubuntu installation tasks"
  include_tasks: install_cmake_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: "[CMAKE] Windows installation tasks"
  include_tasks: install_cmake_windows.yml
  when: ansible_os_family == 'Windows'
